---
- hosts: staging-web-app
  tasks:
    - name: install nginx
      yum: name=nginx state=present
      
    - name: delete nginx APP_H5
      file: path=/usr/share/nginx/html/APP_H5 state=absent
      
    - name: delete nginx APP_NEW
      file: path=/usr/share/nginx/html/APP_NEW state=absent      
      
    - name: upload build
      copy: src={{ci_project_dir}}/ dest=/usr/share/nginx/html mode=777
      
    - name: start nginx
      service: name=nginx state=started